name: Flutter Native Integration Tests with Headless emulator

on:
  push:
    branches: [ main, master ]
  pull_request:

concurrency:
  group: integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Flutter pub get
        run: flutter pub get

      - name: Run integration tests on headless emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33                # 30+ is fine; 33 is modern/stable
          target: google_apis
          arch: x86_64
          profile: pixel_6
          emulator-options: >-
            -no-snapshot
            -no-snapshot-save
            -no-boot-anim
            -noaudio
            -gpu swiftshader_indirect
            -no-window
          disable-animations: true
          script: |
            set -euxo pipefail
            adb wait-for-device
            flutter doctor -v

            # Optional warm-up build
            flutter build apk --debug

            # Run tests (auto-detect emulator ID)
            DEVICE_ID=$(adb devices | awk 'NR==2 {print $1}')
            flutter test integration_test -d "$DEVICE_ID"

            # Gracefully kill emulator to avoid teardown flake
            adb -s "$DEVICE_ID" emu kill || true
